### ISSUE TITLE
Support for GML

### ISSUE THREAD

**Issue by zouroboros** [thisiswhereitype/gmlp#29]
For a university project I had to implement a parser for the [GML](https://en.wikipedia.org/wiki/Graph_Modelling_Language) format, since no parser seems to be available for haskell. I would like to make the code available to other haskell users. Instead of publishing it as a standalone hackage package this poroject seems to be the right place. 

Would do you think about that? Do you have any preferences on which parser framework to use (I used a custom recursive descent parser but it needs some polishing anyway so I wanted to port it to something like parsec anyway)?

**Comment by snowleopard** [comment]
@zouroboros It would be great if you add your GML parser to Pangraph!

I don't have any preference for the parser library. Personally, I wanted to give a try to [Megaparsec](http://hackage.haskell.org/package/megaparsec) for some time (just interested to see how well it works), but it may be an overkill for your purposes.

@thisiswhereitype Do you have any preferences/suggestions?

**Comment by zouroboros** [comment]
I I had some spare time and implemented the parser with [Attoparsec](https://hackage.haskell.org/package/attoparsec-0.13.2.2). You can find my work [here](https://github.com/zouroboros/pangraph/tree/feature/gml-support/src/Pangraph/GML). I implemented most of the functionality but its missing documentation and a few minor changes. I will open a pull request when I'm done.

There are some thinks I noticed:
- In the existing parser the parse function takes a ByteString, this makes it impossible to specify the encoding of a file. Maybe it would be better if the parse functions would take something like Text or at least have parseText functions.
- Pangraph represents the attributes of edges and nodes as a pair of ByteStrings, in the GML format node/edge attributes can be Strings, Texts or even Maps. IMHO it would be good to not loose these type informations by converting all them to a ByteString. Also maybe it would be better to change the type of the attribute keys to Text or something similar. With ByteStrings two identical Attributes could end up differently depending on how the keys and value are encoded in a ByteString. The same applies to using ByteStrings for vertex/edge ids.

**Comment by snowleopard** [comment]
@zouroboros Awesome, thank you!

Pangraphs's API is experimental, so any improvements are welcome! I fully agree that switching to `Text` makes sense as otherwise we'll hit encoding issues.

For node/edge attributes, perhaps we could parameterise the datatype with the type of attributes? Do you have any other solution in mind?

**Comment by zouroboros** [comment]
I would probably parametrize the Pangraph type with the type of the vertex and edge values such as:
`data Pangraph v e`. That would allow to have for example `Pangraph () ()` if Im only interested in the structure of the graph but also something complex `Pangraph (Map String String) (Map String String)`. 

To make it easier to use pangraph with standard graphs it would probably be sensible to introduce a sum type such as `data Value = Integer Integer | Double Doube | Boolean Boolean | String String`  and have a default Pangraph type like `type AttributeGraph = Pangraph [(String, Value)] [(String, Value)]`. 

This would also be the type that the parse Functions return and the write functions take. Maybe one could even implement a type class `class Serialize a where serialize :: a -> [(String, Value)]` and have write functions that allow writing of graphs whose vertex/edge values have an instance of Serialize. The same could be done for parseing.

**Comment by thisiswhereitype** [comment]
I will change to Text shortly.

- I like the idea of parameterized graphs. I had wanted a function `structralEq :: Pangraph -> Pangraph -> Bool` and this provides a very flexible alternative. But can you expand on:
> use pangraph with standard graphs

 - I like the sum type idea
```haskell
type Attribute = [(Text, Value)]
data Value = Integer Integer | Double Double | Boolean Boolean | String String
```
What is gained from having this Value type over using `Text` and `read`? But upon serialization or parsing a graph is it not just moving the conversion to/from Text around? 
Also I will write a benchmark to see what the runtime impact of the Sum type is. i will create a new issue for Sum types and reference you in thread @zouroboros ?

**Comment by zouroboros** [comment]
With standard graph I meant graphs where the vertices and edges have multiple properties, i.e. a labelled graph. I used the term standard graph because this is the model that for example gml or most graph databases like [neo4j](https://neo4j.com/) use.

> What is gained from having this Value type over using Text and read?

The advantage of the sum type over Text is that the type of a value is not lost. For example gml, but also other formats have the object, string, float, bool and int as types. When we represent all values as bytestrings or text the writer (or any user of a pangraph) has no way of knowing if the bytestring "1" (or text) was originally supposed to be a string or an int. For this reason the `GmlWriter` writes every value in a pangraph as a string even if it was originally a float or int.

> i will create a new issue for Sum types and reference you in thread @zouroboros ?

Yes, I would also be willing to start working on this, but I probably don't have time till october
